config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder

  has_many :technologies
  accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body, :main_image, :thumb_image

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(width: '600', height: '400')
    self.thumb_image ||= Placeholder.image_generator(width: '350', height: '200')
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]

  layout "portfolio"

  access all: [:show, :index],
         user: { except: [:destroy, :new, :create, :update, :edit] },
         site_admin: :all
         
  def index
    @portfolios = Portfolio.all
  end

  def show
  end

  def new
    @portfolio = Portfolio.new
    3.times { @portfolio.technologies.build }
  end

  def edit
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully destroyed.' }
    end
  end

  private
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :body,
                                        technologies_attributes: [:name])
    end

end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <ul>
    <%= f.fields_for :technologies do |technology_form| %>
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio.html.erb
<p><%= link_to portfolio.title, portfolio_show_path(portfolio) %></p>

<p><%= portfolio.subtitle %></p>

<p><%= portfolio.body %></p>

<%= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %>

<%= link_to "Edit", edit_portfolio_path(portfolio) if logged_in?(:site_admin) %>
<%= link_to "Delete", portfolio_path(portfolio), method: :delete, data: { confirm: 'Are you sure? '} if logged_in?(:site_admin) %>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create New Portfolio Item", new_portfolio_path if logged_in?(:site_admin) %>

<%= render @portfolios %>

app/views/portfolios/new.html.erb
<h1>Create New Portfolio</h1>

<%= render 'form', portfolio: @portfolio %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio.main_image %>

<h1><%= @portfolio.title %></h1>

<em><%= @portfolio.subtitle %></em>

<p><%= @portfolio.body %></p>

<h2>Tech Used:</h2>
<% @portfolio.technologies.each do |t| %>
  <p><%= t.name %></p>
<% end %>